api:test:
  stage: test
  image: gradle:7.0.2-jdk16
  script:
    - cd api
    - gradle test
  only:
    changes:
      - .gitlab-ci.yml
      - api/**/*

api:build:
  stage: build
  script:
    - cd api
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE/api_builder:latest --target builder .
    - docker build --tag $CI_REGISTRY_IMAGE/api:latest .
    - docker push $CI_REGISTRY_IMAGE/api_builder:latest
    - docker push $CI_REGISTRY_IMAGE/api:latest
  only:
    changes:
      - .gitlab-ci.yml
      - api/**/*

api:deploy:
  stage: deploy
  script:
    - cd api
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/api:latest
    - apk add --update --no-cache curl bash nodejs
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku container:login
    - docker tag $CI_REGISTRY_IMAGE/api:latest registry.heroku.com/social-network-404/web
    - docker push registry.heroku.com/social-network-404/web
    - heroku maintenance:on -a social-network-404
    - echo "Run migrations on DB..."
    - >
      docker run --rm
      -e DB_URL=$STAGING_DB_URL
      -e DB_USER=$STAGING_DB_USER
      -e DB_PASSWORD=$STAGING_DB_PASSWORD
      $CI_REGISTRY_IMAGE/api_builder:latest
      gradle flywayMigrate
    - heroku container:release web -a social-network-404
    - heroku maintenance:off -a social-network-404
  only:
    changes:
      - .gitlab-ci.yml
      - api/**/*
